### ISSUE TITLE
Is this repository still maintained ?

### ISSUE THREAD

**Issue by adrienball** [scrapinghub/python-crfsuite#117]
Given the commit history and the number of issues left with no answer, it seems that this repository is no longer maintained.
If that's the case, it could be great to make it official by adding a note in the README, so that people know that they are on their own when relying on `python-crfsuite`.
Thanks

**Comment by rec** [comment]
This is a developed dependency of the widely-used nltk toolkit so the fact that [this repo is broken for Mac OS](https://github.com/scrapinghub/python-crfsuite/pull/105) means that nltk is also broken for development on Mac OS.

**Comment by kmike** [comment]
Hey! This repo is maintained on a best-effort basis, but not super-actively. Thanks for bringing up installation issues; we'll try fixing the faster next time.
