### ISSUE TITLE
Release new version to PyPI

### ISSUE THREAD

**Issue by wannaphong** [scrapinghub/python-crfsuite#139]
Hello! My projects use python-crfsuite and It is break installation with Python 3.10.

Can you release new version of python-crfsuite to PyPI?

**Comment by dkrylovsb** [comment]
🙏

**Comment by christianbundy** [comment]
cc: @kmike

**Comment by Gerrit-K** [comment]
The wheels are now built & tested in every PR as well as each merge. The only thing missing now is a fresh GitHub release that would then trigger uploading the wheels to PyPI. 
@kmike @fgregg can this just be done or does it need more preparation? (e.g. do we need to increment to `0.9.8` or something?)

**Comment by fgregg** [comment]
i’ll cut a release tonight

**Comment by christianbundy** [comment]
Thanks! Can't wait.

**Comment by fgregg** [comment]
released!
