### ISSUE TITLE
use pypa's cibuildwheel for wheel building

### ISSUE THREAD

**Issue by fgregg** [scrapinghub/python-crfsuite#140]
hi y'all. I've really appreciated using pypa's [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) for handling the complexity of building lots of wheels for different versions of python, OSes, and architectures.

would y'all be interested in a PR to use cibuildwheel?

**Comment by fgregg** [comment]
@Gerrit-K , thanks! i made a couple of comments.

**Comment by Gerrit-K** [comment]
Thanks again, @fgregg, for reviewing and merging my PR! I think we can close this issue then, right?
