### ISSUE TITLE
Fail to open .crf file with path containing utf-8 characters such as 'ö'

### ISSUE THREAD

**Issue by Bringers** [scrapinghub/python-crfsuite#157]
I am using this in a project on a Swedish windows computer. For some reason windows names the admin user folder to "Administratör" (swedish for "Administrator"). I would love to rename this folder but since it is the highest admin on this PC it is tricky to rename (I have tried).

Trying to use "TTS" text to speach and they use your tagger.
There I get the following issue at

```
File "pycrfsuite/_pycrfsuite.pyx", line 572, in pycrfsuite._pycrfsuite.Tagger.open
UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 20: ordinal not in range(128)
```

The line calling this looks like this

`self.crf_tagger.open(str(crf_tagger))`

where
str(crf_tagger) evaluates to something like "C:\Users\Administratör....."

Could someone fix this? I am not confident enough to make a PR on my own here.
I am guessing that you need to introduce utf-8 support in this project somewhere. (or make it possible to configure)

**Comment by fgregg** [comment]
closed by https://github.com/scrapinghub/python-crfsuite/commit/4014eb0244af8bdfbe58662e95acd7fb50bdb1e5
