### ISSUE TITLE
Could someone make a win32 wheel?

### ISSUE THREAD

**Issue by tunabee** [scrapinghub/python-crfsuite#29]
I'd love to use this library (well, I'd love to use usaddress), but I do not have access to a C++ compiler at work. Would it be possible for someone to please create a Python 3.5.1-compatible Win32 wheel of this?

**Comment by kmike** [comment]
@tunabee I don't have Windows machine around, so making these wheels manually is not an option - even if we manage to create it once it is likely I won't be able to do that in future. 
But it should be possible to use AppVeyor to build Windows wheels (see https://github.com/ogrisel/python-appveyor-demo). Pull requests are welcome :)

**Comment by fgregg** [comment]
I'd be happy to make this PR. Would you like it to deploy to pypi, or just build an artifact that you can upload to pypi manually?

**Comment by kmike** [comment]
@fgregg great, thanks! both are fine; I prefer auto deployment to pypi slightly more.

**Comment by fgregg** [comment]
hi @kmike, it looks like if you push a tag then, the window binary builds will deploy to pypi 

I set up the windows deploy script to only attempt to push to pypi on tagged commits.

**Comment by kmike** [comment]
Hey @fgregg,

0.9 release has 0.9 git tag, and I've started appveyor job manually, but for some reason wheels were not uploaded to pypi, and there were no errors. Suggestions are appreciated!

**Comment by kmike** [comment]
See e.g. https://ci.appveyor.com/project/kmike/python-crfsuite/build/job/8n173g4xsp824mwh

**Comment by fgregg** [comment]
hmm.. Appveyor doesn't seem to be seeing your tag. How are you adding the tag? 

This is how i do it:

```python
git tag v5.6.2
git push --tags origin master
```

when I do that, I see the appveyor in the interface. For example, this commit has the awesome tag "v1.5.6fixpassword" https://ci.appveyor.com/project/fgregg/dedupe/build/1.0.692

**Comment by kmike** [comment]
I'm using Sourcetree as a git frontend, but it must do the same; you can see 0.9 tag in github interface (e.g. in Releases tab, or in branch -> tags dropdown). 

Are you adding tag after pushing the commit, or at the same time? .. it shouldn't matter for appveyor though because I started the build manually, when all commits and tags were already on github.

**Comment by fgregg** [comment]
Is it possible that you have the "don't build tags" option selected in the appveyor settings? 

https://ci.appveyor.com/project/kmike/python-crfsuite/settings

**Comment by fgregg** [comment]
The order of adding tags doesn't seem to matter for me.

**Comment by kmike** [comment]
No, this option is not set. Even if the option is set Appveyour should have detected the tag, right? But the UI doesn't show the tag for me, only a branch and a commit number. I've just restarted the build ("build latest commit"), but it is the same - no tag in the UI.

**Comment by fgregg** [comment]
Okay, I'll open up a ticket on appveyor and tag you.

**Comment by kmike** [comment]
Thank you @fgregg!

**Comment by fgregg** [comment]
Can you check https://developer.github.com/webhooks/testing/ to make sure that github delivered tag to appveyor?

**Comment by kmike** [comment]
@fgregg hm, no, it seems I can't because I'm not an admin of this repo. //cc @tpeng

**Comment by fgregg** [comment]
Oh.. looks like there is a known problem with SourceTree and github tags. http://help.appveyor.com/discussions/problems/3960-build-on-tag-wrongly-thinks-its-on-a-different-branch-than-master#comment_38902190

**Comment by fgregg** [comment]
can you try pushing a tag using the command line interface?

**Comment by kmike** [comment]
Hm, what's wrong with me, my git and appveyor? I tried to 

1. Add 'tmp' tag using command-line, push it to github, run a new build - nothing changed;
2. Add a new commit, add 'tmp2' tag to it (all using command-line), push the commit and the tag to github, run a new build - it still doesn't show any tags: https://ci.appveyor.com/project/kmike/python-crfsuite

**Comment by fgregg** [comment]
Hmm.. let's check the "recent deliveries" first, and then go from there.

**Comment by fgregg** [comment]
@kmike take a look at this: http://help.appveyor.com/discussions/questions/2133-deploy-setting-for-nuget#comment_39282593

It looks like both of the tags you made on the command line were annotated tags. Can you try again with a "lightweight" tag

**Comment by fgregg** [comment]
ping @kmike

**Comment by kmike** [comment]
Hey @fgregg,

Didn't know about lightweight vs annotated tags. But I was using 'git tag' without any options to create tmp and tmp2 tags, and `git show` tells that they are lightweight (I'm reading https://git-scm.com/book/en/v2/Git-Basics-Tagging). To check if it helps I also created an annotated "tmp3" tag for the last commit and pushed it, but appveyor still doesn't see it.

**Comment by fgregg** [comment]
weird @kmike, I thought that your previous tags were annotated tags because they have... annotations https://github.com/tpeng/python-crfsuite/releases/tag/tmp2

Okay, thanks for trying.

**Comment by kmike** [comment]
Yeah, that's weird - locally `git show` shows Tagger/Date only for tmp3; for tmp and tmp2 it just shows commit information.

**Comment by fgregg** [comment]
I know it's dumb but could you just do

```git tag tmp4```

and push that tag?

**Comment by fgregg** [comment]
@kmike 

```
If -m <msg> or -F <file> is given and -a, -s, and -u <keyid> are absent, -a is implied.

Otherwise just a tag reference for the SHA-1 object name of the commit object is created (i.e. a lightweight tag).
```

all the tags you have pushed so far have a message, which suggests that they are not lightweight tags.

**Comment by kmike** [comment]
> `git tag tmp4` and push that tag

This is what I did for tmp and tmp2.. `git tag tmp; git push --tags`, nothing fancy. Just did it for tmp4 and tmp5. Here: https://github.com/tpeng/python-crfsuite/tags you can see that these tags are marked as 2 days old, i.e. with the commit date. Annotated tag (tmp3) as shown as ~40 minutes old because it has dateinformation.

**Comment by fgregg** [comment]
Okay, thanks @kmike, I opened up an issue at appveyor here: http://help.appveyor.com/discussions/problems/5704-appveyor-is-not-buliding-lightweight-tags

**Comment by kmike** [comment]
Thanks @fgregg!

**Comment by fgregg** [comment]
appveyor responded http://help.appveyor.com/discussions/problems/5704-appveyor-is-not-buliding-lightweight-tags#comment_41565659

```


Hi Forest,

Tag can only be recognized if build started by webhook. However this build seems to be started with UI or API. Can you (or @kmike) please check Webhooks settings and history for that project?

Thanks!
Ilya.
```

**Comment by kmike** [comment]
@fgregg wow, that was helpful! We moved repo to another location (it is now in /scrapinghub org); I configured automatic appveyor builds, pushed a tag (using SourceTree), and wheels start to upload to pypi: https://pypi.python.org/pypi/python-crfsuite/0.9! Thanks a ton.

**Comment by fgregg** [comment]
yay! thanks for persisting, my users will really appreciate it.

**Comment by fgregg** [comment]
Looks like you can close this one too!

**Comment by kmike** [comment]
The ticket mentions a wheel for Python 3.5.1, but unfortunately there is no 3.5 wheel. But yeah, let's close it in favor of https://github.com/scrapinghub/python-crfsuite/issues/26.
