### ISSUE TITLE
WinError 2 - Missing file / when installing

### ISSUE THREAD

**Issue by Vladisls** [scrapinghub/python-crfsuite#31]
$ pip install python-crfsuite
Collecting python-crfsuite
  Using cached python-crfsuite-0.8.4.tar.gz
Installing collected packages: python-crfsuite
  Running setup.py install for python-crfsuite
    Complete output from command c:\users\vlats\appdata\local\programs\python\python35-32\python.exe -c "import setuptools, tokenize;**file**='C:\Users\Vlats\AppData\Local\Temp\pip-build-k0g40k7c\python-crfsuite\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record C:\Users\Vlats\AppData\Local\Temp\pip-6zahugn5-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.5
    creating build\lib.win32-3.5\pycrfsuite
    copying pycrfsuite_dumpparser.py -> build\lib.win32-3.5\pycrfsuite
    copying pycrfsuite_logparser.py -> build\lib.win32-3.5\pycrfsuite
    copying pycrfsuite__init__.py -> build\lib.win32-3.5\pycrfsuite
    running build_ext
    building 'pycrfsuite._pycrfsuite' extension
    error: [WinError 2] The system cannot find the file specified

```
----------------------------------------
```

Command "c:\users\vlats\appdata\local\programs\python\python35-32\python.exe -c "import setuptools, tokenize;**file**='C:\Users\Vlats\AppData\Local\Temp\pip-build-k0g40k7c\python-crfsuite\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record C:\Users\Vlats\AppData\Local\Temp\pip-6zahugn5-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Vlats\AppData\Local\Temp\pip-build-k0g40k7c\python-crfsuite

**Comment by tkakar** [comment]
I am getting same error. Is there any solution to this issue? Any suggestion will be highly appreciated.

**Comment by jlucier** [comment]
You need this: https://www.microsoft.com/en-us/download/details.aspx?id=44266

I got the same error output you did, but a coworker of mine got the following. That's how we found the solution:

python -m pip install python-crfsuite
Collecting python-crfsuite
  Using cached python-crfsuite-0.8.4.tar.gz
Installing collected packages: python-crfsuite
  Running setup.py install for python-crfsuite ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\mweinb~1\\appdata\\local\\temp\\pip-build-hivnxb\\python-crfsuite\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\mweinb~1\appdata\local\temp\pip-izyeu8-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-2.7
    creating build\lib.win32-2.7\pycrfsuite
    copying pycrfsuite\_dumpparser.py -> build\lib.win32-2.7\pycrfsuite
    copying pycrfsuite\_logparser.py -> build\lib.win32-2.7\pycrfsuite
    copying pycrfsuite\__init__.py -> build\lib.win32-2.7\pycrfsuite
    running build_ext
    building 'pycrfsuite._pycrfsuite' extension
    error: Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat). Get it from http://aka.ms/vcpython27

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\mweinb~1\\appdata\\local\\temp\\pip-build-hivnxb\\python-crfsuite\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\mweinb~1\appdata\local\temp\pip-izyeu8-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\mweinb~1\appdata\local\temp\pip-build-hivnxb\python-crfsuite\

**Comment by fgregg** [comment]
Will be superseded by #29
