### ISSUE TITLE
whl file for Python 3.5 / Windows x64

### ISSUE THREAD

**Issue by ngrjs** [scrapinghub/python-crfsuite#50]
I'm getting vcvarsall.bat error , Is there anyway I can get whl file for Python 3.5 / Windows x64

**Comment by kmike** [comment]
There are currently some issues with building crfsuite on Windows + Python 3.5 - see https://github.com/scrapinghub/python-crfsuite/issues/26.

**Comment by jithurjacob** [comment]
same issue

**Comment by nchervyakov** [comment]
I uploaded a wheel here: https://github.com/scrapinghub/python-crfsuite/issues/51#issuecomment-283244262

**Comment by kmike** [comment]
Fixed by #66.
