### ISSUE TITLE
Problem with compiling for Python 3.5 under Windows 10 x64

### ISSUE THREAD

**Issue by nchervyakov** [scrapinghub/python-crfsuite#51]
I had a problem when tried to compile this library. The problem was the following:
Compiler said thet the following definitions from **python-crfsuite/crfsuite/include/os.h**  conflict with such definitions from system <math.h>:
`#define isfinite    _finite`
`#define snprintf    _snprintf`

I changed them to the following:
`#define my_isfinite    _finite`
`#define my_snprintf    _snprintf`
And also fixed all places in the library where these definitions are used, and then everything compiled perfectly.

**Comment by jithurjacob** [comment]
@nchervyakov can you please share the compiled wheel file or changed source file so that it would be easy for all people facing the same issue?

**Comment by nchervyakov** [comment]
@jithurjacob , I uploaded compiled library, changed source files from crfsuite, and a patch file with changes. I hope it will help.
[python_crfsuite-0.9.1-py3.5-win-amd64.egg_with_patches.zip](https://github.com/scrapinghub/python-crfsuite/files/807050/python_crfsuite-0.9.1-py3.5-win-amd64.egg_with_patches.zip)

**Comment by nchervyakov** [comment]
I also prepared the wheel:
[python_crfsuite-0.9.1-cp35-none-win_amd64.whl.zip](https://github.com/scrapinghub/python-crfsuite/files/809707/python_crfsuite-0.9.1-cp35-none-win_amd64.whl.zip)

**Comment by jithurjacob** [comment]
@nchervyakov It is working for me. Thanks a lot

**Comment by zvodd** [comment]
As a work around a manual build and install can be done (with git and Visual Studio 2014/2015 installed):
```
git clone "https://github.com/scrapinghub/python-crfsuite.git"
cd python-crfsuite
git clone "https://github.com/chokkan/crfsuite.git"
git clone "https://github.com/chokkan/liblbfgs"
python setup.py build
python setup.py install
```

**Comment by fgregg** [comment]
@kmike, this is now a problem for the last two release of python. Thoughts on how we might address this?

**Comment by kmike** [comment]
@fgregg I think we should make a crfsuite fork with necessary fixes, and use it as a git submodule instead of the official crfsuite. I'm fine with switching to e.g. datamade's crfsuite fork :)

**Comment by fgregg** [comment]
@kmike okay, sounds good!

**Comment by fgregg** [comment]
Okay now we have a new problem:

```bash
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Icrfsuite/include/ -Icrfsuite/lib/cqdb/include -Iliblbfgs/include -Ipycrfsuite -Icrfsuite/win32 -Iinclude -Ic:\python35\include -Ic:\python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt" /EHsc /Tppycrfsuite/_pycrfsuite.cpp /Fobuild\temp.win32-3.5\Release\pycrfsuite/_pycrfsuite.obj
    _pycrfsuite.cpp
    crfsuite/win32\stdint.h(331): error C2371: 'uint32_t': redefinition; different basic types
    pycrfsuite/_pycrfsuite.cpp(402): note: see declaration of 'uint32_t'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
```

My suspicion is we don't want to to include win32/stdint.h at all for msvc 2015
https://ci.appveyor.com/project/kmike/python-crfsuite-mhi5h/build/1.0.40/job/5p568q2j12a1yt0o#L60
