### ISSUE TITLE
CI builds for building wheels for OS X and manywheels

### ISSUE THREAD

**Issue by fgregg** [scrapinghub/python-crfsuite#52]
Hi @kmike,

Would you be open to a PR that amended the `.travis.yml` file to build OS X and manylinux wheels and deployed them to pypi (as the appveyor scripts does now)?

**Comment by kmike** [comment]
Sure, that'd be awesome.

**Comment by kmike** [comment]
Fixed by https://github.com/scrapinghub/python-crfsuite/issues/53.
