### ISSUE TITLE
[Question] How to use chokkan's forward backward implementation ? 

### ISSUE THREAD

**Issue by ntugce** [scrapinghub/python-crfsuite#54]
Hi,
I would like to how could I use chokkan's implementation here on[ forward backward algorithm](https://github.com/chokkan/crfsuite/blob/8c0028c5070546a5fc08d2c8175ab244c618f35f/lib/crf/src/crf1d_context.c).
I would be very happy if you could help me out.
Thanks !

**Comment by kmike** [comment]
Hi @ntugce,

python-crfsuite doesn't currently provide wrappers for these inner parts of crfsuite, so it won't help. You can use this algorithm as a part of training process, but not on its own - this is not implemented in this wrapper.

**Comment by ntugce** [comment]
Alright then, thanks for the quick reply.
